name: Build PhotoBooth

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install deps
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build app
      run: |
        pyinstaller \
        --windowed \
        --target-arch universal2 \
        --name PhotoBooth \
        app/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: PhotoBooth
        path: dist/PhotoBooth.app