name: Build PhotoBooth macOS

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set environment variables for universal build
        run: |
          echo "ARCHFLAGS='-arch x86_64 -arch arm64'" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Reinstall watchdog as universal2
        run: |
          pip uninstall -y watchdog
          ARCHFLAGS="-arch x86_64 -arch arm64" pip install --no-binary=:all: watchdog

      - name: Build macOS App
        run: |
          pyinstaller \
            --windowed \
            --target-arch universal2 \
            --name PhotoBooth \
            app/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PhotoBooth-mac
          path: dist/PhotoBooth.app
